export const DQ_SET_TAGS = 'DQ_SET_TAGS';
export const DQ_SET_AUTHORS = 'DQ_SET_AUTHORS';
export const DQ_SET_QUOTES = 'DQ_SET_QUOTES';
export const DQ_HANDLE_CLICK_TAG = 'DQ_HANDLE_CLICK_TAG';
export const DQ_HANDLE_CLICK_AUTHOR = 'DQ_HANDLE_CLICK_AUTHOR';
export const DQ_CREATE_FILTEREDQUOTES = 'DQ_CREATE_FILTEREDQUOTES';
export const DQ_TOGGLE_MOODPAGE = 'DQ_TOGGLE_MOODPAGE';
export const DQ_SET_CURRENT_QUOTE = 'DQ_SET_CURRENT_QUOTE';
export const DQ_TOGGLE_FILTERMODAL = 'DQ_TOGGLE_FILTERMODAL';
export const DQ_REFRESH_FILTEREDQUOTES = 'DQ_REFRESH_FILTEREDQUOTES';
export const DQ_EXPLORE_MORE_TAGS = 'DQ_EXPLORE_MORE_TAGS';
export const DQ_SET_TAGCONTAINER_SCRLLHEIGHT =
  'DQ_SET_TAGCONTAINER_SCRLLHEIGHT';
export const DQ_SET_TAGCONTAINERHEIGHT = 'DQ_SET_TAGCONTAINERHEIGHT';
export const DQ_TAG_INC_EXPLOREMORE_COUNT = 'DQ_TAG_INC_EXPLOREMORE_COUNT';
export const DQ_RESET_TAG_EXPLOREMORE_COUNT = 'DQ_RESET_TAG_EXPLOREMORE_COUNT';
export const DQ_AUTHOR_INC_EXPLOREMORE_COUNT =
  'DQ_AUTHOR_INC_EXPLOREMORE_COUNT';
export const DQ_RESET_AUTHOR_EXPLOREMORE_COUNT =
  'DQ_RESET_AUTHOR_EXPLOREMORE_COUNT';
export const HIDE_QUOTE = 'HIDE_QUOTE';
export const DQ_SET_MAINCONTAINERHEIGHT = 'DQ_SET_MAINCONTAINERHEIGHT';
export const DQ_TOGGLE_EDIT_QUOTETEXT = 'DQ_TOGGLE_EDIT_QUOTETEXT';
export const DQ_SET_EDIT_QUOTETEXT = 'DQ_SET_EDIT_QUOTETEXT';
export const DQ_INITIATE_EDITQUOTETEXT = 'DQ_INITIATE_EDITQUOTETEXT';
export const DQ_HANDLE_EDITQUOTESUCCESS = 'DQ_HANDLE_EDITQUOTESUCCESS';
export const DQ_RSEST_EDIT_QUOTETEXT_STATE = 'DQ_RSEST_EDIT_QUOTETEXT_STATE';
export const DQ_DELETE_DRAGSTART = 'DQ_DELETE_DRAGSTART';
export const DQ_DELETE_DRAGSTART_RESET = 'DQ_DELETE_DRAGSTART_RESET';
export const DQ_DELETE_DRAGEND = 'DQ_DELETE_DRAGEND';
export const DQ_RESET_QUOTES_POST_DELETE = 'DQ_RESET_QUOTES_POST_DELETE';
export const DQ_RESET_SELECTQUOTES_POST_DELETE =
  'DQ_RESET_SELECTQUOTES_POST_DELETE';
export const DQ_QUOTE_DELETE_REQUEST_SUCCESS =
  'DQ_QUOTE_DELETE_REQUEST_SUCCESS';
export const DQ_DELETE_RESET = 'DQ_DELETE_RESET';
export const DQ_INITIATE_DELETE_REQUEST = 'DQ_INITIATE_DELETE_REQUEST';
export const DQ_RESET_QUOTE_STATE = 'DQ_RESET_QUOTE_STATE';
export const DQ_HIDE_INTROANIMATION = 'DQ_HIDE_INTROANIMATION';
export const DQ_TOGGLE_ACTIONBUTTONS = 'DQ_TOGGLE_ACTIONBUTTONS';
export const DQ_TOGGLE_AUTHORPROFILEDRAWER = 'DQ_TOGGLE_AUTHORPROFILEDRAWER';
