export const DQ_SET_TAGS = 'DQ_SET_TAGS';
export const DQ_SET_AUTHORS = 'DQ_SET_AUTHORS';
export const DQ_SET_QUOTES = 'DQ_SET_QUOTES';
export const DQ_HANDLE_CLICK_TAG = 'DQ_HANDLE_CLICK_TAG';
export const DQ_HANDLE_CLICK_AUTHOR = 'DQ_HANDLE_CLICK_AUTHOR';
export const DQ_CREATE_FILTEREDQUOTES = 'DQ_CREATE_FILTEREDQUOTES';
export const DQ_TOGGLE_MOODPAGE = 'DQ_TOGGLE_MOODPAGE';
export const DQ_SET_CURRENT_QUOTE = 'DQ_SET_CURRENT_QUOTE';
export const DQ_TOGGLE_FILTERMODAL = 'DQ_TOGGLE_FILTERMODAL';
export const DQ_REFRESH_FILTEREDQUOTES = 'DQ_REFRESH_FILTEREDQUOTES';
export const DQ_EXPLORE_MORE_TAGS = 'DQ_EXPLORE_MORE_TAGS';
export const DQ_SET_TAGCONTAINER_SCRLLHEIGHT =
  'DQ_SET_TAGCONTAINER_SCRLLHEIGHT';
export const DQ_SET_TAGCONTAINERHEIGHT = 'DQ_SET_TAGCONTAINERHEIGHT';
export const DQ_TAG_INC_EXPLOREMORE_COUNT = 'DQ_TAG_INC_EXPLOREMORE_COUNT';
export const DQ_RESET_TAG_EXPLOREMORE_COUNT = 'DQ_RESET_TAG_EXPLOREMORE_COUNT';
export const DQ_AUTHOR_INC_EXPLOREMORE_COUNT =
  'DQ_AUTHOR_INC_EXPLOREMORE_COUNT';
export const DQ_RESET_AUTHOR_EXPLOREMORE_COUNT =
  'DQ_RESET_AUTHOR_EXPLOREMORE_COUNT';
export const HIDE_QUOTE = 'HIDE_QUOTE';
