export const DQ_SET_TAGS = 'DQ_SET_TAGS';
export const DQ_SET_AUTHORS = 'DQ_SET_AUTHORS';
export const DQ_SET_QUOTES = 'DQ_SET_QUOTES';
export const DQ_HANDLE_CLICK_TAG = 'DQ_HANDLE_CLICK_TAG';
export const DQ_HANDLE_CLICK_AUTHOR = 'DQ_HANDLE_CLICK_AUTHOR';
export const DQ_CREATE_FILTEREDQUOTES = 'DQ_CREATE_FILTEREDQUOTES';
